apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.override.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: api-audit
  name: api-audit
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.override.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: api-audit
    spec:
      containers:
      - env:
        - name: dbhost
          value: db
        - name: dbname
          value: dashboarddb
        image: registry.gitlab.com/clvrcloud/hygieia-api-audit
        name: api-audit
        ports:
        - containerPort: 8080
        - containerPort: 8081
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 495m
            memory: 565Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
