apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: db-setup
  name: db-setup
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: db-setup
    spec:
      containers:
      - image: registry.gitlab.com/clvrcloud/hygieia-db-setup
        name: db-setup
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
