apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.override.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hygieia-feature-jira-collector
  name: hygieia-feature-jira-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.override.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: hygieia-feature-jira-collector
    spec:
      containers:
      - env:
        - name: JIRA_BASE_URL
          value: https://*.atlassian.net/
        - name: JIRA_BOARD_AS_TEAM
          value: "true"
        - name: JIRA_CREDENTIALS
          value: $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        - name: MONGO_PORT
          value: tcp://db:27017
        image: registry.gitlab.com/clvrcloud/hygieia-feature-jira-collector
        name: hygieia-feature-jira-collector
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 495m
            memory: 565Mi
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
