apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
      - image: registry.gitlab.com/clvrcloud/hygieia-ui
        name: ui
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 10m
            memory: 50Mi
        env:
        - name: API_HOST
          value: api
        - name: API_PORT
          value: "8080"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
